version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5448:5432"
  user-service:
    build: ./
    ports:
      - "8080:8080"