spring:
  datasource:
    password: postgres
    platform: postgres
    url: jdbc:postgresql://postgres:5448/postgres
    username: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
  hibernate:
    ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog.xml
rabbitmq:
  host: rabbitmq
  queue: userEventsQueue